name: Node 14 Alpine

on:
  push:
    branches:
      - main
    paths:
      - "node-14-alpine/Dockerfile"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 4s1-org/node
  IMAGE_VERSION: 14-alpine

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
